### ISSUE TITLE
How to train Chinese corpus after downloading the universal-dependencies-2.0 ?

### ISSUE THREAD

**Issue by 12343954** [dsindex/syntaxnet#24]
How to train Chinese corpus after downloading the universal-dependencies-2.0 ?

thank you so much !

I couldn't find the method.

**Comment by dsindex** [comment]
hello~ 

since the [Syntaxnet](https://github.com/tensorflow/models/tree/master/syntaxnet#how-to-use-this-library) recommends to use DRAGNN, 

i also recommend you to follow [this tutorial](https://github.com/dsindex/syntaxnet#dragnn).

after downloading UD Chinese corpus, you can use `train_dragnn.sh` to train a model.
(please edit train_dragnn.sh for proper corpus path)

you can use `test_dragnn.sh` for tagging and parsing.

these model is supposed to get a pre-segmented sentence as input.
but, in Chinese, there is no space in input sentence. 

therefore, you should segment raw sentence(unsegmented) before feeding the model.

if you want to train a segmentation model, you can refer [codes](https://github.com/tensorflow/models/tree/master/syntaxnet/dragnn/tools)
```
1. segmenter_trainer.py
2. segmenter-evaluator.py
```

**Comment by 12343954** [comment]
hi, thank for your reply !
I follow this step, https://github.com/dsindex/syntaxnet/issues/21
and I compile the first line , then error for this
`ERROR: /Users/mac/NLP/models/syntaxnet/work/dragnn_examples/BUILD:62:1: no such package 'dragnn/protos': BUILD file not found on package path and referenced by '//work/dragnn_examples:dragnn-deps'.
ERROR: Analysis of target '//work/dragnn_examples:write_master_spec' failed; build aborted.`

![qq 20170421120209](https://cloud.githubusercontent.com/assets/1804003/25262465/cca89d26-268a-11e7-9dc8-be036cf1a156.jpg)

**Comment by dsindex** [comment]
@12343954  did you install the most recent version of the Syntaxnet?
your directory should look like 
```
$ cd /Users/mac/NLP/models/syntaxnet
$ ls
... g3doc/   third_party/  util/ README.md   dragnn/  syntaxnet/  tools/  work/
WORKSPACE  examples/   tensorflow/   ....
```

**Comment by 12343954** [comment]
print(tf.__version__)
1.0.1

**Comment by 12343954** [comment]
![image](https://cloud.githubusercontent.com/assets/1804003/25262574/8c0794b0-268b-11e7-8cb5-7c82286c6d24.png)
it seemed not the latest version

**Comment by 12343954** [comment]
@dsindex how to upgrade to the latest version？TF and syntaxnet. Uninstall and reinstall again？

**Comment by dsindex** [comment]
you need to install syntaxnet and dragnn from source by following guide.
https://github.com/tensorflow/models/blob/master/syntaxnet/README.md
once you install it, every code for syntaxnet and dragnn will use the tensorflow submodule inside regardless tf module which is installed system wide.

**Comment by 12343954** [comment]
from source ? oh, it's little difficult for me!
thank you very much , I'll try .
